FROM mhart/alpine-node:16.4.2 as builder

# install dependencies
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --immutable --immutable-cache --check-cache

# Copy all local files into the image.
COPY . .

EXPOSE 3000
CMD ["yarn", "dev", "--host", "0.0.0.0"]